"""
EduPredict Pro — Central configuration.
All display-time data citations and year references pull from this file.
When BLS releases updated OES data, change DATA_YEAR and BLS_SOURCE here only.
"""

import os
import secrets
from typing import Dict, List

# ── Scope ─────────────────────────────────────────────────────────────────────
MVP_STATES: List[str] = ["CT", "NY", "MA"]

PROGRAM_TYPES: List[str] = [
    "MS in AI",
    "BS in AI",
    "AI in Cybersecurity",
]

STUDENT_TYPES: List[str] = ["International", "Domestic"]

ACADEMIC_TERMS: Dict[str, str] = {
    "FA26": "Fall 2026",
    "SP27": "Spring 2027",
    "FA28": "Fall 2028",
}

SCENARIOS: List[str] = ["Baseline", "Optimistic", "Pessimistic", "Conservative"]

STATE_NAMES: Dict[str, str] = {
    "CT": "Connecticut",
    "NY": "New York",
    "MA": "Massachusetts",
}

# ── Data vintage ───────────────────────────────────────────────────────────────
# Change these two lines when BLS publishes updated OES data.
DATA_YEAR: int = 2024
BLS_SOURCE: str = "Bureau of Labor Statistics OES, May 2024"
BLS_PROJ_SOURCE: str = "BLS Employment Projections 2023\u201333 (published Sep 2024)"
NACE_SOURCE: str = "NACE Salary Survey, Spring 2024"
EMPLOYER_DATA_DATE: str = "March 2025"   # update when employers_2024.csv is refreshed
LAST_UPDATED: str = "March 2025"

# ── Security ───────────────────────────────────────────────────────────────────
# Never hard-code a secret key. Set SECRET_KEY in your environment or .env file.
SECRET_KEY: str = os.environ.get("SECRET_KEY", secrets.token_hex(32))

# ── Application metadata ───────────────────────────────────────────────────────
APP_TITLE = "EduPredict Pro"
APP_SUBTITLE = "AI and cybersecurity labor market intelligence — CT, NY, MA"

# ── Forecasting defaults ───────────────────────────────────────────────────────
DEFAULT_SCENARIO = "Baseline"
DEFAULT_STATE = "CT"
DEFAULT_PROGRAM = "MS in AI"
DEFAULT_STUDENT_TYPE = "International"
DEFAULT_TERM = "FA26"

# ── UI settings ────────────────────────────────────────────────────────────────
PAGE_TITLE = "EduPredict Pro"
LAYOUT = "wide"

# ── File paths ─────────────────────────────────────────────────────────────────
DATA_RAW_PATH = "data/raw"
DATA_PROCESSED_PATH = "data/processed"
MODELS_PATH = "models"

# Primary data files — generated by data/fetch_real_data.py
BLS_OES_FILE       = "data/raw/bls_oes_2024.csv"          # updated BLS OES
BLS_PROJ_FILE      = "data/raw/bls_projections_2033.csv"
EMPLOYERS_FILE     = "data/raw/employers_2024.csv"         # Team A delivers
GRAD_SALARIES_FILE = "data/raw/grad_salaries_2024.csv"     # Team A delivers
IPEDS_INST_FILE    = "data/raw/ipeds_institutions.csv"
INST_PROGRAMS_FILE = "data/raw/institutions_programs_2024.csv"  # Team A delivers

# Legacy / fallback files (kept for compatibility)
BLS_OES_FILE_LEGACY    = "data/raw/bls_oes_2023_real.csv"
GRAD_SAL_FILE_LEGACY   = "data/raw/grad_salaries_real.csv"
EMPLOYERS_FILE_LEGACY  = "data/raw/employers_real.csv"

# Removed: ipeds_enrollment_sample.csv (fabricated — deleted in Phase 1)
# Removed: ui/app.py (Streamlit version — replaced by app_dashboard.py)

# ── Source URLs ────────────────────────────────────────────────────────────────
DATA_SOURCES = {
    "IPEDS":  "https://nces.ed.gov/ipeds/",
    "BLS":    "https://www.bls.gov/",
    "Census": "https://www.census.gov/",
    "NACE":   "https://www.naceweb.org/job-market/compensation/",
}
